# 🧹 Module 3 — Class 1 Homework: Data Cleaning

**Topic:** Cleaning — missing values, duplicates, type conversion

## 📋 What you have to do

This notebook **already has working code**. Your job:

1. **Run every cell from top to bottom** — it should run with no errors.
2. **Add a comment on EVERY code cell** that explains what the cell does, in your own words.
   - Use `#` to write comments inside the code cell.
   - Write at least 1 short sentence per cell. Longer is better.
3. **Save your notebook** as `Module<X>_Class<Y>_<YourName>.ipynb` and submit.

**Example of a good commented cell:**

```python
# Count how many customers churned vs stayed
# value_counts() returns the number of rows for each unique value
df['Churn'].value_counts()
```

**Example of a BAD comment (do not do this):**

```python
# count
df['Churn'].value_counts()
```

---

In [1]:
# Import libraries for working with data, math operations, and charts
# pandas is used for tables, numpy for calculations, and matplotlib for visualization

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings; warnings.filterwarnings('ignore')

# Load the customer churn dataset from an online CSV file
url = 'https://raw.githubusercontent.com/IBM/telco-customer-churn-on-icp4d/master/data/Telco-Customer-Churn.csv'
df = pd.read_csv(url)

# Convert TotalCharges column to numeric values
# If conversion fails, replace errors with NaN and then fill them with 0
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce').fillna(0)

# Print the size of the dataset to see how many rows and columns were loaded
print('Loaded:', df.shape)

Loaded: (7043, 21)

### Cell 1 — see how many missing values per column

In [10]:
# Check how many missing values exist in each column
# isnull() finds missing values and sum() counts them

df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

### Cell 2 — check how many duplicate rows we have

In [11]:
# Count how many duplicate rows exist in the dataset
# duplicated() checks repeated rows and sum() counts them

print('Duplicates:', df.duplicated().sum())

Duplicates: 0

### Cell 3 — make a copy and add a fake missing value to test fillna

In [12]:
# Create a copy of the dataset so the original data stays unchanged
df_test = df.copy()

# Add fake missing values into the tenure column for testing
# This helps us practice handling missing data

df_test.loc[0:9, 'tenure'] = np.nan

# Count how many missing values now exist in tenure
print('Missing tenure now:', df_test['tenure'].isnull().sum())

Missing tenure now: 10

### Cell 4 — fill missing tenure with the median

In [13]:
# Find the median value of the tenure column
# Median is the middle value and is often used to fill missing data

median_tenure = df_test['tenure'].median()

# Replace missing tenure values with the median
df_test['tenure'] = df_test['tenure'].fillna(median_tenure)

# Check if missing values were successfully filled
print('After fillna, missing:', df_test['tenure'].isnull().sum())

# Print the median value that was used
print('Median used:', median_tenure)

After fillna, missing: 0
Median used: 29.0

### Cell 5 — fill missing TotalCharges with 0

In [14]:
# Replace missing values in TotalCharges with 0
# fillna(0) is useful when missing values should become zero

df['TotalCharges'] = df['TotalCharges'].fillna(0)

# Verify that there are no missing values left
print('TotalCharges missing after fillna:', df['TotalCharges'].isnull().sum())

TotalCharges missing after fillna: 0

### Cell 6 — drop duplicate rows

In [15]:
# Save the number of rows before removing duplicates
before = len(df)

# Remove duplicate rows from the dataset
df = df.drop_duplicates()

# Save the number of rows after cleaning
after = len(df)

# Print how many duplicate rows were removed
print(f'Before: {before}, After: {after}, Dropped: {before - after}')

Before: 7043, After: 7043, Dropped: 0

### Cell 7 — convert SeniorCitizen from 0/1 to 'No'/'Yes'

In [16]:
# Convert SeniorCitizen values from numbers into readable text
# 0 becomes No and 1 becomes Yes

df['SeniorCitizen'] = df['SeniorCitizen'].map({0: 'No', 1: 'Yes'})

# Count how many Yes and No values exist
df['SeniorCitizen'].value_counts()

Series([], Name: count, dtype: int64)

### Cell 8 — strip whitespace from gender column

In [17]:
# Remove extra spaces from values in the gender column
# strip() helps clean text data

df['gender'] = df['gender'].str.strip()

# Count how many rows belong to each gender
df['gender'].value_counts()

gender
Male      3555
Female    3488
Name: count, dtype: int64

---

## 📤 Submit

Comment every cell. Push to `module-3/class_1/submissions/<YourName>/`.