# Series and DataFrames (maps to lecture section “Series and DataFrames”)

In [122]:
import pandas as pd #Upload pandas for data preparation
import seaborn as sns #Upload seaborn for data visualization and tips dataset
import numpy as np #Upload numpy for data preparation

In [123]:
df = pd.DataFrame({
"name": ["Ali", "Zara", "Jasur"],
"age": [22, 28, 31],
"city": ["Tashkent", "Samarkand", "Bukhara"]
}) #Data frame

Series age column

In [124]:
df["age"] # Age column

0    22
1    28
2    31
Name: age, dtype: int64

In [125]:
df[["name", "age"]] # Name and Age columns

    name  age
0    Ali   22
1   Zara   28
2  Jasur   31

In [126]:
print(df.index) # Show index

RangeIndex(start=0, stop=3, step=1)

Add three more rows to df

In [127]:
new_data = pd.DataFrame({
    "name": ["Omar", "Sofia", "David"],
    "age": [25, 30, 29],
    "city": ["Almaty", "Kyiv", "Berlin"]
})
# new dataframe
df = pd.concat([df, new_data], ignore_index=True) # add data ignore index
display(df)

    name  age       city
0    Ali   22   Tashkent
1   Zara   28  Samarkand
2  Jasur   31    Bukhara
3   Omar   25     Almaty
4  Sofia   30       Kyiv
5  David   29     Berlin

# Loading and Exploring (maps to lecture section “Loading and Exploring”)

In [128]:
tips_df = sns.load_dataset('tips')
print("Built-in 'tips' dataset head:")
tips_df = pd.DataFrame(tips_df)
print("Tips DataFrame head:")
display(tips_df)

Built-in 'tips' dataset head:
Tips DataFrame head:

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [129]:
tips_df['day']

0       Sun
1       Sun
2       Sun
3       Sun
4       Sun
       ...
239     Sat
240     Sat
241     Sat
242     Sat
243    Thur
Name: day, Length: 244, dtype: category
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

In [130]:
tips_df['time']

0      Dinner
1      Dinner
2      Dinner
3      Dinner
4      Dinner
        ...
239    Dinner
240    Dinner
241    Dinner
242    Dinner
243    Dinner
Name: time, Length: 244, dtype: category
Categories (2, object): ['Lunch', 'Dinner']

In [131]:
tips_df.head(5) #Tipss dataset all column and 5 rows

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [132]:
tips_df.shape #Dataset shape col x row

(244, 7)

In [133]:
tips_df.info() # Column elements, column name, types, there are null elemens , dimension type

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [134]:
tips_df.describe() #Dataframe numbers element coun, mean, std, min, iqr, max

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [135]:
tips_df.isna().sum() #Data null elements summa each columns

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

# Filtering, GroupBy, Merging (maps to lecture section “Filtering, GroupBy, Merging”)

## Boolean filtering

In [136]:
tips_df[(tips_df['total_bill'] >=20) & (tips_df['sex'] == 'Male')] # Short command and fast read  use &, parentheses not to avoid confusion

     total_bill   tip   sex smoker  day    time  size
2         21.01  3.50  Male     No  Sun  Dinner     3
3         23.68  3.31  Male     No  Sun  Dinner     2
5         25.29  4.71  Male     No  Sun  Dinner     4
7         26.88  3.12  Male     No  Sun  Dinner     4
15        21.58  3.92  Male     No  Sun  Dinner     2
..          ...   ...   ...    ...  ...     ...   ...
227       20.45  3.00  Male     No  Sat  Dinner     4
230       24.01  2.00  Male    Yes  Sat  Dinner     4
237       32.83  1.17  Male    Yes  Sat  Dinner     2
239       29.03  5.92  Male     No  Sat  Dinner     3
241       22.67  2.00  Male    Yes  Sat  Dinner     2

[70 rows x 7 columns]

## GroupBy: split-apply-combine

In [137]:
tips_df.groupby('sex')['total_bill'].mean() #Group gender men total bill

/tmp/ipykernel_11706/3812446729.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tips_df.groupby('sex')['total_bill'].mean() #Group gender men total bill

sex
Male      20.744076
Female    18.056897
Name: total_bill, dtype: float64

In [138]:
tips_df.groupby('sex')['smoker'].count() # Gender smoker count

/tmp/ipykernel_11706/3372964764.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tips_df.groupby('sex')['smoker'].count() # Gender smoker count

sex
Male      157
Female     87
Name: smoker, dtype: int64

In [139]:
tips_df.groupby('sex').agg({'total_bill': ['mean', 'min', 'max'], 'tip': ['mean', 'min','max'], 'size': ['mean', 'min', 'max'], 'smoker': 'count'}) # Describe gender elements

/tmp/ipykernel_11706/2713482208.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tips_df.groupby('sex').agg({'total_bill': ['mean', 'min', 'max'], 'tip': ['mean', 'min','max'], 'size': ['mean', 'min', 'max'], 'smoker': 'count'}) # Describe gender elements

       total_bill                    tip                 size         smoker
             mean   min    max      mean  min   max      mean min max  count
sex
Male    20.744076  7.25  50.81  3.089618  1.0  10.0  2.630573   1   6    157
Female  18.056897  3.07  44.30  2.833448  1.0   6.5  2.459770   1   6     87

##Merging

In [140]:
day_type_lookup = pd.DataFrame({
    'day': ['Thur', 'Fri', 'Sat', 'Sun'],
    'day_type': ['Weekday', 'Weekday', 'Weekend', 'Weekend']
})

print("Lookup DataFrame:")
display(day_type_lookup)

Lookup DataFrame:

    day day_type
0  Thur  Weekday
1   Fri  Weekday
2   Sat  Weekend
3   Sun  Weekend

In [141]:
tips_df_merged = pd.merge(tips_df, day_type_lookup, on='day', how='left')

print("Merged DataFrame (first 5 rows with new 'day_type' column):")
display(tips_df_merged.head())

Merged DataFrame (first 5 rows with new 'day_type' column):

   total_bill   tip     sex smoker  day    time  size day_type
0       16.99  1.01  Female     No  Sun  Dinner     2  Weekend
1       10.34  1.66    Male     No  Sun  Dinner     3  Weekend
2       21.01  3.50    Male     No  Sun  Dinner     3  Weekend
3       23.68  3.31    Male     No  Sun  Dinner     2  Weekend
4       24.59  3.61  Female     No  Sun  Dinner     4  Weekend

In [142]:
region_names = ['west', 'south', 'north', 'east']

# Create a Series of regions with the same length as tips_df
# This will be used to add a 'region' column to tips_df
tips_df_regions = pd.Series(np.random.choice(region_names, size=len(tips_df)))

In [143]:
# Create a copy of tips_df to add the new 'region' column
tips_df_with_regions = tips_df.copy()
tips_df_with_regions['region'] = tips_df_regions

print("DataFrame with 'region' column (first 5 rows):")
display(tips_df_with_regions.head())

DataFrame with 'region' column (first 5 rows):

   total_bill   tip     sex smoker  day    time  size region
0       16.99  1.01  Female     No  Sun  Dinner     2   west
1       10.34  1.66    Male     No  Sun  Dinner     3  north
2       21.01  3.50    Male     No  Sun  Dinner     3  south
3       23.68  3.31    Male     No  Sun  Dinner     2   east
4       24.59  3.61  Female     No  Sun  Dinner     4   east