# 🔤 Module 3 — Class 3 Homework: Categorical Encoding

**Topic:** Encoding — get_dummies, OneHotEncoder, binary mapping

## 📋 What you have to do

This notebook **already has working code**. Your job:

1. **Run every cell from top to bottom** — it should run with no errors.
2. **Add a comment on EVERY code cell** that explains what the cell does, in your own words.
   - Use `#` to write comments inside the code cell.
   - Write at least 1 short sentence per cell. Longer is better.
3. **Save your notebook** as `Module<X>_Class<Y>_<YourName>.ipynb` and submit.

**Example of a good commented cell:**

```python
# Count how many customers churned vs stayed
# value_counts() returns the number of rows for each unique value
df['Churn'].value_counts()
```

**Example of a BAD comment (do not do this):**

```python
# count
df['Churn'].value_counts()
```

---

In [1]:
# Import the libraries needed for data analysis and visualization
# Load the customer churn dataset and convert TotalCharges to numeric values
# Replace invalid values with 0 so the column can be used correctly

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings; warnings.filterwarnings('ignore')

url = 'https://raw.githubusercontent.com/IBM/telco-customer-churn-on-icp4d/master/data/Telco-Customer-Churn.csv'
df = pd.read_csv(url)
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce').fillna(0)
print('Loaded:', df.shape)

Loaded: (7043, 21)

### Cell 1 — see which columns are categorical (text)

In [2]:
# Find all columns that contain text (categorical data)
# This helps us understand which columns may need encoding before modeling

cat_cols = df.select_dtypes(include='object').columns.tolist()
print('Categorical columns:', cat_cols)
print('Total:', len(cat_cols))

Categorical columns: ['customerID', 'gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'Churn']
Total: 17

### Cell 2 — look at one categorical column

In [3]:
# Count how many customers belong to each contract type
# value_counts() shows the frequency of each category

df['Contract'].value_counts()

Contract
Month-to-month    3875
Two year          1695
One year          1473
Name: count, dtype: int64

### Cell 3 — use pd.get_dummies to one-hot encode Contract

In [4]:
# Convert the Contract column into separate binary columns using one-hot encoding
# Each category gets its own 0/1 column

dummies = pd.get_dummies(df['Contract'], prefix='Contract')
print('Shape before:', df[['Contract']].shape, '-> after:', dummies.shape)
dummies.head()

Shape before: (7043, 1) -> after: (7043, 3)

   Contract_Month-to-month  Contract_One year  Contract_Two year
0                     True              False              False
1                    False               True              False
2                     True              False              False
3                    False               True              False
4                     True              False              False

### Cell 4 — drop_first=True (to avoid the dummy variable trap)

In [5]:
# Apply one-hot encoding again but remove the first category
# drop_first=True helps avoid duplicate information between encoded columns

dummies2 = pd.get_dummies(df['Contract'], prefix='Contract', drop_first=True)
print('With drop_first:', dummies2.shape)
dummies2.head()

With drop_first: (7043, 2)

   Contract_One year  Contract_Two year
0              False              False
1               True              False
2              False              False
3               True              False
4              False              False

### Cell 5 — use OneHotEncoder from sklearn

In [6]:
# Use sklearn's OneHotEncoder to transform PaymentMethod into numerical columns
# This is another popular way to perform one-hot encoding

from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse_output=False)
encoded = ohe.fit_transform(df[['PaymentMethod']])
encoded_df = pd.DataFrame(encoded, columns=ohe.get_feature_names_out(['PaymentMethod']))
encoded_df.head()

,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,1.0
2,0.0,0.0,0.0,1.0
3,1.0,0.0,0.0,0.0
4,0.0,0.0,1.0,0.0

### Cell 6 — binary Yes/No → 1/0 mapping

In [7]:
# Convert Yes/No values into 1/0 numbers
# Binary mapping is useful for machine learning models

df['Churn_bin'] = df['Churn'].map({'No': 0, 'Yes': 1})
df[['Churn', 'Churn_bin']].head()

  Churn  Churn_bin
0    No          0
1    No          0
2   Yes          1
3    No          0
4   Yes          1

### Cell 7 — encode multiple columns at once

In [8]:
# Encode multiple categorical columns at the same time
# All selected text columns are converted into numerical features

multi = pd.get_dummies(df[['gender', 'Contract', 'PaymentMethod']], drop_first=True)
print('Shape:', multi.shape)
multi.head()

Shape: (7043, 6)

,gender_Male,Contract_One year,Contract_Two year,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,False,False,False,False,True,False
1,True,True,False,False,False,True
2,True,False,False,False,False,True
3,True,True,False,False,False,False
4,False,False,False,False,True,False

---

## 📤 Submit

Comment every cell. Push to `module-3/class_3/submissions/<YourName>/`.